[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc-version = "0.8.20"
optimizer = true
optimizer-runs = 200
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
base_mainnet = "${RPC_BASE_MAINNET}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", chain_id = 8453, url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain_id = 84532, url = "https://api-sepolia.basescan.org/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"
