[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.20"
optimizer = true
optimizer-runs = 200

# Add the Base network details here.
# Use environment variables for your RPC URL and API keys for security.
[rpc_endpoints]
base_mainnet = "${RPC_BASE_MAINNET}"
base_sepolia = "${RPC_BASE_SEPOLIA}"

# Etherscan configuration for contract verification
[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", chain_id = 8453 }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain_id = 84532 }

# The "url" field is a custom property for Etherscan to correctly
# identify the block explorer for a given network.
[etherscan.base_mainnet]
url = "[https://api.basescan.org/api](https://api.basescan.org/api)"

[etherscan.base_sepolia]
url = "[https://api-sepolia.basescan.org/api](https://api-sepolia.basescan.org/api)"






[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]


[rpc_endpoints]
default_network = "http://127.0.0.1:8545"

mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimismSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygonZkEvm = "https://zkevm-rpc.com"
polygonZkEvmTestnet = "https://rpc.public.zkevm-test.net"
gnosis = "https://rpc.gnosischain.com"
chiado = "https://rpc.chiadochain.net"
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
scrollSepolia = "https://sepolia-rpc.scroll.io"
scroll = "https://rpc.scroll.io"
pgn = "https://rpc.publicgoods.network"
pgnTestnet = "https://sepolia.publicgoods.network"


localhost = "http://127.0.0.1:8545"

[etherscan]
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }



[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview